#pragma config(Sensor, S1,     bls,            sensorEV3_Color)
#pragma config(Sensor, S2,     rs,             sensorEV3_Color)
#pragma config(Sensor, S3,     ls,             sensorEV3_Color)
#pragma config(Sensor, S4,     brs,            sensorEV3_Color)
#pragma config(Motor,  motorA,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          lt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rsum=0,lsum=0,ll=0,rl=0, brsum=0,blsum=0,brl=0,bll=0;
//declare variable
void reset()
{
	nMotorEncoder[lm]=0;
	nMotorEncoder[rm]=0;
	nMotorEncoder[rt]=0;
	nMotorEncoder[lt]=0;
}
void go(int a,int b)
{
	motor[lm]=-a;
	motor[rm]=-b;
}
void go_en(int a, int b, int c)
{
	reset();
	if(a>0||b>0)
		while(nMotorEncoder[rm]>=-c)
			go(a,b);
	else
		while(nMotorEncoder[rm]<=c)
			go(a,b);
	go(0,0);
}
void halt()
{
	go(0,0);
	delay(500);
}
void get()
{
	reset();

	while(nMotorEncoder[lm]>=-850)
		go(50,40);

	go(50,40);
	for(int i=1 ; i<=5 ; i++)
	{
		rsum+=SensorValue[rs];
		lsum+=SensorValue[ls];
		brsum+=SensorValue[brs];
		blsum+=SensorValue[bls];

		delay(3);
	}
	ll=(lsum/5)*0.95;
	rl=(rsum/5)*0.95;
	bll=(blsum/5)*0.95;
	brl=(brsum/5)*0.95;

	displayBigTextLine(1,"%d",ll);
	displayBigTextLine(3,"%d",rl);
	displayBigTextLine(5,"%d",bll);
	displayBigTextLine(7,"%d",brl);
}
void adjust(int a)
{
	for(int i=5 ; i>=1 ; i--)
	{
		go(10*i,10*i);
		for (int j=1;j<=a;j++)
		{
			delay(10);
			if(SensorValue[ls]>=ll)
				go(0,20);
			if(SensorValue[rs]>=rl)
				go(20,0);
			if(SensorValue[ls]>=ll&&SensorValue[rs]>=rl)
				return;
		}
	}
}

task main()
{
	get();
	//get white sensor value

	go_en(47,40,680);
	//pass white area

	/*while(nMotorEncoder[rt]>=-1630)
		motor[rt]=-100;
	//unfold arm

	while(nMotorEncoder[rt]<=0)
		motor[rt]=100;
	//fold arm

	motor[rt]=0;
	//stop arm  */
	go_en(15,12,370);
	//go fountain
	adjust(68);
	//go to line

	go_en(50,40,195);
	//smooth(40,20,250);
	//go to black line

	//adjust(20);
	//go to line

	while(nMotorEncoder[lt]>=-4860)
		motor[lt]=-100;
	//down arm
	motor[lt]=0;

	halt();
	halt();
	halt();

	while(nMotorEncoder[lt]<=0)
		motor[lt]=100;
	//up arm

	motor[lt]=0;

	go_en(40,40,25);
	//go to samgak
	while(nMotorEncoder[rt]>=-1400)
		motor[rt]=-100;
	//put samgak
	motor[rt]=0;
	go_en(-40,-40,200);
	while(nMotorEncoder[rt]<=100)
		motor[rt]=100;
	go(-100,-96);
	while(1)
	{
		if(nMotorEncoder[rt]>1000)
			motor[rt]=0;
		if(nMotorEncoder[lm]>2900)
			break;
	}
}
