#pragma config(Sensor, S2,     rs,             sensorEV3_Color)
#pragma config(Sensor, S3,     ls,             sensorEV3_Color)
#pragma config(Motor,  motorA,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          lt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rsum=0,lsum=0,ll=0,rl=0;
//declare variable
void reset()
{
	nMotorEncoder[lm]=0;
	nMotorEncoder[rm]=0;
	nMotorEncoder[rt]=0;
	nMotorEncoder[lt]=0;
}
void go(int a,int b)
{
	motor[lm]=-a;
	motor[rm]=-b;
}
void halt()
{
	go(0,0);
	delay(400);
}
void get()
{
	reset();
	go(40,40);
	for(int i=1 ; i<=5 ; i++)
	{
		rsum+=SensorValue[rs];
		lsum+=SensorValue[ls];
		delay(3);
	}
	ll=(lsum/5);
	rl=(rsum/5);
	displayBigTextLine(1,"%d",ll);
	displayBigTextLine(3,"%d",rl);
}
void go_en(int a, int b, int c)
{
	reset();
	if(a>0||b>0)
		while(nMotorEncoder[rm]>=-c)
			go(a,b);
	else
		while(nMotorEncoder[rm]<=c)
			go(a,b);
	go(0,0);
}
int rvalue()
{
	int rsum=0,rval=0,rmax=0,rmin=100,rsen;
	for(int i=1 ; i<=5 ; i++)
	{
		rsen=SensorValue[rs];
		rsum+=rsen;
		if(rsen>rmax)
			rmax=rsen;
		if(rsen<rmin)
			rmin=rsen;
		delay(1);
	}
	rsum-=rmin;
	rsum-=rmax;
	rval=rsum/3;
	return rval;
}
int lvalue()
{
	int lsum=0,lval=0,lmax=0,lmin=100,lsen;
	for(int i=1 ; i<=5 ; i++)
	{
		lsen=SensorValue(ls);
		lsum+=lsen;
		if(lsen>lmax)
			lmax=lsen;
		if(lsen<lmin)
			lmin=lsen;
		delay(1);
	}
	lsum-=lmin;
	lsum-=lmax;
	lval=lsum/3;
	return lval;
}
void adjust(int a,int b)
{
	for(int i=b ; i>=1 ; i--)
	{
		go(10*i,10*i);
		for (int j=1;j<=a;j++)
		{
			if(SensorValue[ls]>=ll)
				go(0,10);
			if(SensorValue[rs]>=rl)
				go(10,0);
			if(SensorValue[ls]>=ll&&SensorValue[rs]>=rl)
				return;
			delay(1);
		}
	}
}
void smooth_go(int a,int b,int k)
{
	for(int i=5 ; i>=1 ; i--)
	{
		go((a/5)*i,(b/5)*i);
		for (int j=1;j<=k;j++)
			delay(1);
	}
}

task main()
{
	get();
	go_en(40,40,500);
	go_en(100,100,3070);
	halt();

	go_en(-30,-30,220);
	halt();
	go_en(0,30,210);
	halt();
	go_en(30,30,890);
	halt();
	go_en(0,20,225);
	halt();
	go_en(30,30,450);

	while(nMotorEncoder[lt]<=420)
		motor[lt]=100;

	motor[lt]=0;
	delay(400);

	while(nMotorEncoder[lt]<=800)
		motor[lt]=100;
	motor[lt]=0;
	delay(200);

	go_en(-30,-30,200);

	while(nMotorEncoder[lt]>=100)
		motor[lt]=-100;
	motor[lt]=0;

	halt();
	go_en(-10,-50,570);
	halt();
	go_en(30,30,85);
	halt();
	go_en(-35,-35,900);
	go_en(-25,-25,60);
	reset();
	while(nMotorEncoder[rt]>-200)
		motor[rt]=-60;
	motor[rt]=0;
	reset();
	while(nMotorEncoder[rt]<200)
		motor[rt]=60;
	motor[rt]=0;
	reset();
	go_en(10,10,50);
	time1(T1)=0;
	while(nMotorEncoder[rt]>-1000&&time1(T1)<=2500)
		motor[rt]=-100;
	motor[rt]=0;
	while(nMotorEncoder[rt]<0)
		motor[rt]=100;
	motor[rt]=0;
	go_en(10,10,300);
	go_en(100,-90,1000);

}
