#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          lt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void go(int a,int b)
{
	motor[lm]=-a;
	motor[rm]=-b;
}

void halt()
{
	go(0,0);
	delay(400);
}

task main()
{

	nMotorEncoder[lm]=0;
	nMotorEncoder[rm]=0;
	nMotorEncoder[rt]=0;
	nMotorEncoder[lt]=0;

	while(1)
	{
		motor[rt]=100;
		if(nMotorEncoder[rt]>=800)
			motor[rt]=0;

		go(41,40);
		if(nMotorEncoder[lm]<=-920)
		{
			go(0,0);
			break;
		}
	}
	//go + arm unfold

	while(1)
	{
		go(-20,-20);
		if(nMotorEncoder[lm]>=-820)
			go(0,0);

		motor[rt]=-20;
		if(nMotorEncoder[rt]<=620)
		{
			motor[rt]=0;
			break;
		}
	}
	//back + arm fold

	while(1)
	{
		go(30,33);

		if(nMotorEncoder[lm]<=-1675)
		{
			go(0,0);
			break;
		}
	}
	//go
	time1(T1)=0;
	while(1)
	{
		motor[rt]=-50;

		if(nMotorEncoder[rt]<=-70 || time1(T1)>=2500)
		{
			motor[rt]=0;
			break;
		}
	}
	//arm fold

	while(1)
	{
		motor[rt]=100;
		if(nMotorEncoder[rt]>=1480)
		{
			motor[rt]=0;
			break;
		}
	}
	//arm unfold

	while(1)
	{
		go(-30,-50);
		if(nMotorEncoder[lm]>=-1520)
		{
			go(0,0);
			break;
		}
	}
	// back

	halt();
	//stop

	while(1)
	{
		motor[rt]=-100;
		if(nMotorEncoder[rt]<=1150)
		{
			motor[rt]=0;
			break;
		}
	}
	//arm fold

	while(1)
	{
		motor[rt]=-100;
		go(-20,-27);
		if(nMotorEncoder[rt]<=0)
		{
			motor[rt]=0;
			go(-79,-100);
		}

		if(nMotorEncoder[lm]>=100)
		{
			go(0,0);
			break;
		}
	}// back + fold
}
