#pragma config(Sensor, S2,     rs,             sensorEV3_Color)
#pragma config(Sensor, S3,     ls,             sensorEV3_Color)
#pragma config(Motor,  motorA,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          lt,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void reset()
{
	nMotorEncoder[lm]=0;
	nMotorEncoder[rm]=0;
	nMotorEncoder[rt]=0;
	nMotorEncoder[lt]=0;
}
void go(int a,int b)
{
	motor[lm]=-a;
	motor[rm]=-b;
}
void go_en(int a, int b, int c)
{
	reset();
	if(a>0||b>0)
		while(nMotorEncoder[lm]>=-c)
			go(a,b);
	else
		while(nMotorEncoder[lm]<=c)
			go(a,b);
	go(0,0);
}
task main()
{
	reset();
	go_en(100,100,940);
	go_en(-100,-100,950);
}
