#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
#pragma config(Sensor, S3,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int temp=40,sum=0,k=65;
int hour=12,min=0;
task main()
{
	while(SensorValue[S3]==0)
	{
		if(SensorValue[S1]==1)
		{
			if(temp<99)
			{
				while(SensorValue[S1]==1){}
				temp++;
			}
			else
			{
				eraseDisplay();
				displayBigTextLine(1,"Too High");
				displayBigTextLine(4,"Range: 1 ~99");
				playSound(soundBeepBeep);
				delay(1000);
				eraseDisplay();
			}
		}
		if(SensorValue[S2]==1)
		{
			if(temp>1)
			{
				while(SensorValue[S2]==1){}
				temp--;
			}
			else
			{
				eraseDisplay();
				displayBigTextLine(1,"Too Low");
				displayBigTextLine(4,"Range: 1~99");
				playSound(soundBeepBeep);
				delay(1000);
				eraseDisplay();
			}
		}
		displayBigTextLine(1,"Choose Temp");
		displayBigTextLine(4,"Temp: %d C",temp);
		displayBigTextLine(7,"Red: Up");
		displayBigTextLine(10,"Blue: Down");
		displayBigTextLine(13,"Gray: Select");
	}
	//time--------------------------------------------------
	eraseDisplay();
	delay(1000);
	while(SensorValue[S3]==0)
	{
		if(SensorValue[S1]==1)
		{
			if(hour<=22 && hour>=0)
			{
				while(SensorValue[S1]==1){}
				hour++;
			}
			else if(hour==23)
			{
				while(SensorValue[S1]==1){}
				hour=0;
			}
		}
		if(SensorValue[S2]==1)
		{
			if(min<=58 && min>=0)
			{
				while(SensorValue[S2]==1){}
				min++;
			}
			else if(min==59)
			{
				while(SensorValue[S2]==1){}
				min=0;
			}
		}
		displayBigTextLine(1,"Choose Time");
		if(hour<10)
		{
			if(min<10)
				displayBigTextLine(4,"Time: 0%d : 0%d",hour,min);
			else
				displayBigTextLine(4,"Time: 0%d : %d",hour,min);
		}
		else
		{
			if(min<10)
				displayBigTextLine(4,"Time: %d : 0%d",hour,min);
			else
				displayBigTextLine(4,"Time: %d : %d",hour,min);
		}
		displayBigTextLine(7,"Red: Hour");
		displayBigTextLine(10,"Blue: Min");
		displayBigTextLine(13,"Gray: Select");
	}

	//choose temperature---------------------------------------
	eraseDisplay();
	delay(1000);
	sum+=temp;
	while(SensorValue[S3]==0)
	{
		displayBigTextLine(1,"Press 3rd");
		displayBigTextLine(4,"Button to Stop");
		displayBigTextLine(7,"Temp: %d C",temp);
		if(hour<10)
		{
			if(min<10)
				displayBigTextLine(10,"Time: 0%d : 0%d",hour,min);
			else
				displayBigTextLine(10,"Time: 0%d : %d",hour,min);
		}
		else
		{
			if(min<10)
				displayBigTextLine(10,"Time: %d : 0%d",hour,min);
			else
				displayBigTextLine(10,"Time: %d : %d",hour,min);
		}

		while(1)
		{
			motor[motorA]=100;
			motor[motorB]=100;
			if(nMotorEncoder[motorA]>=temp*k)
				motor[motorA]=0;
			if(nMotorEncoder[motorB]>=(100-temp)*k)
				motor[motorB]=0;
			if(nMotorEncoder[motorA]>=temp*k&&nMotorEncoder[motorB]>=(100-temp)*k)
				break;
		}

	}
	//open valve--------------------------------------------------
	while(1)
	{
		motor[motorA]=-100;
		motor[motorB]=-100;
		if(nMotorEncoder[motorA]<=-400)
			motor[motorA]=0;
		if(nMotorEncoder[motorB]<=-400)
			motor[motorB]=0;
		if(nMotorEncoder[motorA]<=0&&nMotorEncoder[motorB]<=0)
			break;
	}
	//return------------------------------------------------------
	while(true)
	{
		motor[motorA]=100;
		motor[motorB]=100;
		if(nMotorEncoder[motorA]>=0)
			motor[motorA]=0;
		if(nMotorEncoder[motorB]>=0)
			motor[motorB]=0;
		if(nMotorEncoder[motorA]>=0&&nMotorEncoder[motorB]>=0)
			break;
	}


}
